# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'Realm+Unit Test' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for Realm+Unit Test
  #pod 'SwiftyJSON'
  pod 'RealmSwift'

  target 'Realm+Unit TestTests' do
    inherit! :search_paths
    # Pods for testing
  end

end
